swagger: "2.0"
info:
  description: "APIs de Curvas do Transfer Price <img src='https://github.com/rodboza/drawio/blob/master/TRANSFER%20-%20Modelagem.png?raw=true'>"
  version: "1.0.0"
  title: "Swagger im-transfer-price-curva"
tags:
- name: "curva"
  description: "funcionalidades das curvas do Transfer Price"
- name: "execução"
  description: "funcionalidades das Execuções das curvas do Transfer Price"
- name: "pontos"
  description: "funcionalidades dos pontos de uma execução das curvas do Transfer Price"
schemes:
- "https"

paths:
  /curva:
    get:
      tags:
      - "curva"
      summary: "Busca uma curva"
      description: "Retorna os dados cadatrais de uma unica curva"
      produces:
      - "application/json"
      parameters:
      - name: "curvaID"
        in: "query"
        description: "ID da curva para consulta"
        required: true
        type: "integer"
        format: "int64"      
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Curva"
        "400":
          description: "Código de curva invalido"
        "404":
          description: "Curva não encontrada"
          
  /curva/findbyname:
    get:
      tags:
      - "curva"
      summary: "Busca curvas"
      description: "Retorna uma lista curva"
      produces:
      - "application/json"
      parameters:
      - name: "nome"
        in: "query"
        description: "nome ou parte do nome para consulta"
        required: false
        type: "string"

      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ListaCurva"
        "400":
          description: "Código de curva invalido"
        "404":
          description: "Curva não encontrada"
  
  /execucao:

    get:
      tags:
      - "execução"
      summary: "Busca uma Execução de uma curva"
      description: "Retorna os dados de uma unica Execução de uma unica curva"
      produces:
      - "application/json"
      parameters:
      - name: "curvaID"
        in: "query"
        description: "ID da curva para consulta"
        required: true
        type: "integer"
        format: "int64" 
      - name: "execucaoID"
        in: "query"
        description: "ID da execução para consulta"
        required: true
        type: "string"
        format: "date-time" 
      responses:
        "200":
          description: "Operação realizada com sucesso"
          schema:
            $ref: "#/definitions/Execucao"
        "400":
          description: "Código de curva invalido"
        "404":
          description: "Curva não encontrada"

    post:
      tags:
      - "execução"
      summary: "Criar uma nova Execução"
      description: "Gera uma nova Execução para a curva"
      operationId: "EnviaExecucao"
      produces:
      - "application/json"
      parameters:
      - name: "body"
        in: "body"
        description: "ID da curva para consulta"
        required: true
        schema:
            $ref: "#/definitions/ExecucaoCurva"
      responses:
        "200":
          description: "Operação realizada com sucesso"
          schema:
            $ref: "#/definitions/Execucao"
        "400":
          description: "Execução invalida" 


    put:
      tags:
      - "execução"
      summary: "Atualiza o Status da Execução de uma curva"
      description: "Atualiza o Status de uma unica Execução de uma unica curva"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "atualização do status de uma execução"
        required: true
        schema:
          $ref: "#/definitions/Execucao"
      responses:
        "200":
          description: "Operação realizada com sucesso"
          schema:
            $ref: "#/definitions/Execucao"
        "400":
          description: "Código de curva invalido"
        "404":
          description: "Curva não encontrada"    



  /excucao/findbydatahora:
    get:
      tags:
      - "execução"
      summary: "Busca Execuções de uma curva"
      description: "Retorna uma lista de Execuções de uma unica curva"
      produces:
      - "application/json"
      parameters:
      - name: "curvaID"
        in: "query"
        description: "ID da curva para consulta"
        required: true
        type: "integer"
        format: "int64" 
      - name: "dataHoraIncio"
        in: "query"
        description: "Data da execução para consulta"
        required: true
        type: "string"
        format: "date-time" 
      - name: "dataHoraFim"
        in: "query"
        description: "Data da execução para consulta"
        required: true
        type: "string"
        format: "date-time" 
      responses:
        "200":
          description: "Operação realizada com sucesso"
          schema:
            $ref: "#/definitions/ListaExecucao"
        "400":
          description: "Código de curva invalido"
        "404":
          description: "Curva não encontrada"
          
          
  /pontos:
    get:
      tags:
      - "pontos"
      summary: "Busca os pontos de uma Execução de uma curva"
      description: "Retorna uma lista de pontos de uma unica execução  de uma unica curva"
      produces:
      - "application/json"
      parameters:
      - name: "curvaID"
        in: "query"
        description: "ID da curva para consulta"
        required: true
        type: "integer"
        format: "int64" 
      - name: "execucaoID"
        in: "query"
        description: "ID da execução para consulta"
        required: true
        type: "string"
        format: "date-time" 
      responses:
        "200":
          description: "Operação realizada com sucesso"
          schema:
            $ref: "#/definitions/ExecucaoPontos"
        "400":
          description: "Código de curva invalido"
        "404":
          description: "Curva não encontrada"  
    post:
      tags:
      - "pontos"
      summary: "Criar uma nova execução a partir de pontos"
      description: "Gera uma Execução com os pontos passados no post"
      operationId: "EnviaExecucaoPontos"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "enviar pontos para uma nova curva"
        required: true
        schema:
          $ref: "#/definitions/newExecucaoPontos"
      responses:
        "200":
          description: "Operação realizada com sucesso"
          schema:
            $ref: "#/definitions/Execucao"
        "400":
          description: "Execução invalido"          
  /pontos/findbyvencimento:

    get:
      tags:
      - "pontos"
      summary: "Busca os pontos de uma execução de uma curva por vencimento"
      description: "Retorna uma lista de pontos de uma unica execução de uma unica curva baseado numa lista de vencimentos"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "lista de vencimentos a serem pesquisados"
        required: true
        schema:
          $ref: "#/definitions/FindByVencimento"
      responses:
        "200":
          description: "Operação realizada com sucesso"
          schema:
            $ref: "#/definitions/ExecucaoPontos"
        "400":
          description: "Código de curva invalido"
        "404":
          description: "Curva não encontrada"
      deprecated: true



definitions:
  Curva:
    type: "object"
    properties:
      curvaId:
        type: "integer"
        format: "int64"
      nome:
        type: "string"
      idCurvaBase:
        type: "integer"
        format: "int64"
        
  Execucao:
    type: "object"
    properties:
      execucaoId:
        type: "string"
        format: "date-time"
      curvaId:
        type: "integer"
        format: "int64"
      status:
        type: "string"
        enum:
        - "Aguardando Execução"
        - "Em execução"
        - "Aguardando Validação"       
        - "Liberada"     
        
  Ponto:
    type: "object"
    properties:
      vencimento:
        type: "string"
        format: "date"
      valor:
        type: "number"
        format: "double"
        

  ExecucaoPontos:
    type: "object"
    properties:
      curvaId:
        type: "integer"
        format: "int64"
      execucaoId:
        type: "string"
        format: "date-time"
      data-base:
        type: "string"
        format: "date"
      pontos:
        type: "array"
        items:
          $ref: "#/definitions/Ponto"

  newExecucaoPontos:
    type: "object"
    properties:
      curvaId:
        type: "integer"
        format: "int64"
      data-base:
        type: "string"
        format: "date"
      pontos:
        type: "array"
        items:
          $ref: "#/definitions/Ponto"
          
          
  ExecucaoCurva:
    type: "object"
    properties:
      curvaId:
        type: "integer"
        format: "int64"
        
  FindByVencimento:      
    type: "object"
    properties:
      curvaId:
        type: "integer"
        format: "int64"
      execucaoId:
        type: "string"
        format: "date-time"
      vencimentos:
        type: "array"
        items:
          type: "string"
          format: "date"
 
          
  ListaCurva:
    type: "array"
    items:
       $ref: "#/definitions/Curva"
       
  ListaExecucao:
    type: "array"
    items:
       $ref: "#/definitions/Execucao"
       














