swagger: "2.0"
info:
  description: "APIs de Curvas do Transfer Price"
  version: "1.0.0"
  title: "Swagger im-transfer-price-curva"
tags:
- name: "curva"
  description: "funcionalidades das curvas do Transfer Price"
- name: "processamento"
  description: "funcionalidades dos processamentos do Transfer Price"
- name: "pontos"
  description: "funcionalidades dos pontos do Transfer Price"
schemes:
- "https"

paths:
  /curva/findbyname:
    get:
      tags:
      - "curva"
      summary: "Busca curvas"
      description: "Retorna uma lista curva"
      produces:
      - "application/json"
      parameters:
      - name: "nome"
        in: "query"
        description: "nome ou parte do nome para consulta"
        required: false
        type: "string"

      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ListaCurva"
        "400":
          description: "Código de curva invalido"
        "404":
          description: "Curva não encontrada"
  
  /curva/{curvaID}:
    get:
      tags:
      - "curva"
      summary: "Busca uma curva"
      description: "Retorna os dados cadatrais de uma unica curva"
      produces:
      - "application/json"
      parameters:
      - name: "curvaID"
        in: "path"
        description: "ID da curva para consulta"
        required: true
        type: "integer"
        format: "int64"      
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Curva"
        "400":
          description: "Código de curva invalido"
        "404":
          description: "Curva não encontrada"
          
  /curva/{curvaID}/processamento:
    get:
      tags:
      - "processamento"
      summary: "Busca Processamentos de uma curva"
      description: "Retorna uma lista de Processamentos de uma unica curva"
      produces:
      - "application/json"
      parameters:
      - name: "curvaID"
        in: "path"
        description: "ID da curva para consulta"
        required: true
        type: "integer"
        format: "int64" 
      - name: "DataIncio"
        in: "query"
        description: "Data do processamento para consulta"
        required: true
        type: "string"
        format: "date" 
      - name: "DataFim"
        in: "query"
        description: "Data do processamento para consulta"
        required: true
        type: "string"
        format: "date" 
      responses:
        "200":
          description: "Operação realizada com sucesso"
          schema:
            $ref: "#/definitions/ListaProcessamento"
        "400":
          description: "Código de curva invalido"
        "404":
          description: "Curva não encontrada"
    post:
      tags:
      - "processamento"
      summary: "Criar um novo Processamento"
      description: "Gera um novo processamento para a curva"
      operationId: "EnviaProcessamento"
      produces:
      - "application/json"
      parameters:
      - name: "curvaID"
        in: "path"
        description: "ID da curva para consulta"
        required: true
        type: "integer"
        format: "int64" 
      responses:
        "200":
          description: "Operação realizada com sucesso"
          schema:
            $ref: "#/definitions/Processamento"
        "400":
          description: "Processamento invalido"              
  /curva/{curvaID}/processamento/pontos:
    post:
      tags:
      - "pontos"
      summary: "Criar uma novo Processamento a partir de pontos"
      description: "Gera um Processamento com os pontos passados no post"
      operationId: "EnviaProcessamentoPontos"
      produces:
      - "application/json"
      parameters:
      - name: "curvaID"
        in: "path"
        description: "ID da curva para consulta"
        required: true
        type: "integer"
        format: "int64" 
      - in: "body"
        name: "body"
        description: "enviar pontos para uma nova curva"
        required: true
        schema:
          $ref: "#/definitions/ProcessamentoPontos"
      responses:
        "200":
          description: "Operação realizada com sucesso"
          schema:
            $ref: "#/definitions/Processamento"
        "400":
          description: "Processamento invalido"          

  /curva/{curvaID}/processamento/{processamentoID}:
    get:
      tags:
      - "processamento"
      summary: "Busca um Processamento de uma curva"
      description: "Retorna os dados de um unico Processamento de uma unica curva"
      produces:
      - "application/json"
      parameters:
      - name: "curvaID"
        in: "path"
        description: "ID da curva para consulta"
        required: true
        type: "integer"
        format: "int64" 
      - name: "processamentoID"
        in: "path"
        description: "ID do processamento para consulta"
        required: true
        type: "string"
        format: "date-time" 
      responses:
        "200":
          description: "Operação realizada com sucesso"
          schema:
            $ref: "#/definitions/Processamento"
        "400":
          description: "Código de curva invalido"
        "404":
          description: "Curva não encontrada"
    put:
      tags:
      - "processamento"
      summary: "Atualiza o Status de Processamento de uma curva"
      description: "Atualiza o Status de um unico Processamento de uma unica curva"
      produces:
      - "application/json"
      parameters:
      - name: "curvaID"
        in: "path"
        description: "ID da curva para consulta"
        required: true
        type: "integer"
        format: "int64" 
      - name: "processamentoID"
        in: "path"
        description: "ID do processamento para consulta"
        required: true
        type: "string"
        format: "date-time"
      - in: "body"
        name: "body"
        description: "atualização do status de um processamento"
        required: true
        schema:
          $ref: "#/definitions/ProcessamentoStatus"
      responses:
        "200":
          description: "Operação realizada com sucesso"
          schema:
            $ref: "#/definitions/Processamento"
        "400":
          description: "Código de curva invalido"
        "404":
          description: "Curva não encontrada"    

  /curva/{curvaID}/processamento/{processamentoID}/pontos:
    get:
      tags:
      - "pontos"
      summary: "Busca os pontos de um Processamento de uma curva"
      description: "Retorna uma lista de pontos de unico Processamento de uma unica curva"
      produces:
      - "application/json"
      parameters:
      - name: "curvaID"
        in: "path"
        description: "ID da curva para consulta"
        required: true
        type: "integer"
        format: "int64" 
      - name: "processamentoID"
        in: "path"
        description: "ID do processamento para consulta"
        required: true
        type: "string"
        format: "date-time" 
      responses:
        "200":
          description: "Operação realizada com sucesso"
          schema:
            $ref: "#/definitions/ProcessamentoPontos"
        "400":
          description: "Código de curva invalido"
        "404":
          description: "Curva não encontrada"
          
  /curva/{curvaID}/processamento/{processamentoID}/pontos/findbyvencimento:
    get:
      tags:
      - "pontos"
      summary: "Busca os pontos de um Processamento de uma curva por vencimento"
      description: "Retorna uma lista de pontos de unico Processamento de uma unica curva baseado numa lista de vencimentos"
      produces:
      - "application/json"
      parameters:
      - name: "curvaID"
        in: "path"
        description: "ID da curva para consulta"
        required: true
        type: "integer"
        format: "int64" 
      - name: "processamentoID"
        in: "path"
        description: "ID do processamento para consulta"
        required: true
        type: "string"
        format: "date-time" 
        
      - in: "body"
        name: "body"
        description: "lista de vencimentos a serem pesquisados"
        required: true
        schema:
          $ref: "#/definitions/ListaVencimento"
      responses:
        "200":
          description: "Operação realizada com sucesso"
          schema:
            $ref: "#/definitions/ProcessamentoPontos"
        "400":
          description: "Código de curva invalido"
        "404":
          description: "Curva não encontrada"
          
          
          
          
definitions:
  Curva:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      nome:
        type: "string"
      idCurvaBase:
        type: "integer"
        format: "int64"
        
  Processamento:
    type: "object"
    properties:
      id:
        type: "string"
        format: "date-time"
      curvaId:
        type: "integer"
        format: "int64"
      status:
        type: "string"
        enum:
        - "Aguardando Execução"
        - "Em execução"
        - "Aguardando Validação"       
        - "Liberada"     
  Ponto:
    type: "object"
    properties:
      vencimento:
        type: "string"
        format: "date"
      valor:
        type: "number"
        format: "double"
        

  ProcessamentoPontos:
    type: "object"
    properties:
      data-base:
        type: "string"
        format: "date"
      pontos:
        type: "array"
        items:
          $ref: "#/definitions/Ponto"
          
          
  ProcessamentoStatus:
    type: "object"
    properties:
      status:
        type: "string"
        enum:
        - "Aguardando Execução"
        - "Em execução"
        - "Aguardando Validação"       
        - "Liberada"     
          
  ListaCurva:
    type: "array"
    items:
       $ref: "#/definitions/Curva"
       
  ListaProcessamento:
    type: "array"
    items:
       $ref: "#/definitions/Processamento"
       
  
  
  ListaVencimento:
    type: "array"
    items:
      type: "string"
      format: "date"
        
        














